version: '2.3'
services:
  vino_ros:
    image: tiger0421/openvino-ros:latest
    container_name: vino
    network_mode: "host"
    privileged: true
    tty: true
    group_add:
      - video
    environment:
      - MESA_GL_VERSION_OVERRIDE=4.2
      - XAUTHORITY=/tmp/.docker.xauth
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ~/.Xauthority:/home/openvino/.Xauthority:rw
      - ~/share:/home/openvino/share
    devices:
      - /dev/dri:/dev/dri
    command: /bin/bash

  rviz2:
    image: tiger0421/openvino-ros:latest
    container_name: rviz2
    network_mode: "host"
    privileged: true
    tty: true
    group_add:
      - video
    environment:
      - MESA_GL_VERSION_OVERRIDE=4.2
      - XAUTHORITY=/tmp/.docker.xauth
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ~/.Xauthority:/home/openvino/.Xauthority:rw
      - ~/share:/home/openvino/share
    devices:
      - /dev/dri:/dev/dri
    command: /bin/bash -c "source /opt/ros/eloquent/setup.bash; rviz2"

 roscore:
    image: osrf/ros:melodic-desktop-full
    container_name: roscore
    network_mode: "host"
    privileged: true
    tty: true
    working_dir: /root
    group_add:
      - video
    environment:
      - MESA_GL_VERSION_OVERRIDE=4.2
      - XAUTHORITY=/tmp/.docker.xauth
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ~/.Xauthority:/root/.Xauthority:rw
      - ~/share:/root/share:rw
    devices:
      - /dev/dri:/dev/dri
    command: /bin/bash -c ". /opt/ros/melodic/setup.bash; roscore"

  bridge:
    image: ros:eloquent-ros1-bridge
    container_name: ros2-bridge
    network_mode: "host"
    privileged: true
    tty: true
    working_dir: /root
    group_add:
      - video
    environment:
      - MESA_GL_VERSION_OVERRIDE=4.2
      - XAUTHORITY=/tmp/.docker.xauth
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ~/.Xauthority:/root/.Xauthority:rw
      - ~/share:/root/share:rw
    devices:
      - /dev/dri:/dev/dri
    command: /bin/bash -c "ros2 run ros1_bridge dynamic_bridge"


